language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
# before_script: grunt coffee
script: grunt default
after_success:
  - npm install codeclimate-test-reporter
  - node_modules/.bin/istanbul report
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: 1941445c3c9ab126b1cb0218fd37343d6f81f550cb6984ee2a02edab23b72b03
